<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt-BR" xml:lang="pt-BR"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>AWS RE/START – Repositório de Materiais — Tecnologia</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-7869b05831703f3177918bcdc0271c3b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets/logo_senac.png" alt="" class="navbar-logo light-content">
    <img src="./assets/logo_senac.png" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Repositório de Materiais — Tecnologia</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Início</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./fluxograma.html"> 
<span class="menu-text">Fluxograma das trilhas</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-trilhas" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Trilhas</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-trilhas">    
        <li>
    <a class="dropdown-item" href="./trilhas/index.html">
 <span class="dropdown-text">Visão geral das 6 trilhas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./trilhas/trilha-1-ia-aplicada.html">
 <span class="dropdown-text">1 — IA Aplicada</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./trilhas/trilha-2-dados.html">
 <span class="dropdown-text">2 — Dados</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./trilhas/trilha-3-infraestrutura.html">
 <span class="dropdown-text">3 — Infraestrutura, Cloud e Redes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./trilhas/trilha-4-ciberseguranca.html">
 <span class="dropdown-text">4 — Cibersegurança</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./trilhas/trilha-5-programacao.html">
 <span class="dropdown-text">5 — Programação e Desenvolvimento</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./trilhas/trilha-6-produtividade.html">
 <span class="dropdown-text">6 — Produtividade e Citizen Development</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="./como-atualizar.html"> 
<span class="menu-text">Como atualizar</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./changelog.html"> 
<span class="menu-text">Changelog</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
    <a href="./#" title="Repositório" class="quarto-navigation-tool px-1" aria-label="Repositório"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo de leitor">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">AWS RE/START</h1>
<p class="subtitle lead">460h · Trilha 3 — Infraestrutura, Cloud e Redes</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Este é o <strong>repositório de referência dos cursos de Tecnologia do SENAC RJ</strong>, mantido pela <strong>Cápsula de Inovação — Coordenação de Tecnologias</strong>. Reúne, por curso, os quatro blocos de material que o instrutor precisa para planejar e ministrar a oferta:</p>
<ul>
<li><strong>PC — Plano de Curso</strong> (identificação, justificativa, objetivo, organização curricular, avaliação);</li>
<li><strong>PTD — Plano de Trabalho Docente</strong> (situação de aprendizagem, planejamento das aulas, instrumentos de avaliação);</li>
<li><strong>Referências Bibliográficas</strong> (oficiais e de apoio);</li>
<li><strong>Materiais Complementares</strong> (guias do instrutor, datasets, modelos, vídeos, prompts).</li>
</ul>
<p>Cada curso está posicionado dentro de uma das <strong>6 trilhas</strong> do portfólio, com os <strong>pré-requisitos</strong> e o <strong>próximo passo</strong> explícitos — para que o instrutor enxergue não só o curso, mas a jornada do aluno.</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Para começar:</strong> veja o <strong><a href="./fluxograma.html">Fluxograma das trilhas</a></strong> (mapa de todos os cursos, pré-requisitos e progressão), entre pela trilha do seu curso nos cartões abaixo ou consulte o <strong>catálogo de cursos com material publicado</strong> logo a seguir.</p>
</div>
</div>
</div>
<section id="sec-catalogo" class="level2">
<h2 class="anchored" data-anchor-id="sec-catalogo">Catálogo de cursos</h2>
<p>Catálogo completo das <strong>6 trilhas</strong>. Clique no nome do curso para abrir sua página — com <strong>PC</strong>, <strong>PTD</strong>, <strong>referências</strong> e <strong>materiais complementares</strong>. A coluna <strong>Material</strong> indica o estágio: <strong>✅ publicado</strong> (PC/PTD e arquivos <code>.docx</code> oficiais já disponíveis para download) ou <em>estrutura</em> (página criada, conteúdo em preenchimento contínuo).</p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>31 cursos já com material publicado</strong> (PC, PTD e arquivos <code>.docx</code> para download) — cobrindo as trilhas de <strong>IA Aplicada, Dados, Programação, Infraestrutura/Cloud, Cibersegurança e Produtividade</strong>. Os 10 restantes (marcados <em>estrutura</em>) são <strong>propostas/cursos novos</strong> (NC-xx) ainda sem PC/PTD oficial.</p>
</div>
</div>
</div>
<section id="trilha-1-ia-aplicada" class="level4">
<h4 class="anchored" data-anchor-id="trilha-1-ia-aplicada">Trilha 1 — IA Aplicada</h4>
<table class="caption-top table">
<caption>Trilha 1 — IA Aplicada.</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Curso</th>
<th style="text-align: center;">Código</th>
<th style="text-align: center;">CH</th>
<th style="text-align: center;">Status</th>
<th style="text-align: center;">Material</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./cursos/ia-na-pratica/index.html">Inteligência Artificial na Prática</a></td>
<td style="text-align: center;">14149 / 1745.29</td>
<td style="text-align: center;">8h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/ia-sem-misterio/index.html">IA Sem Mistério: Turbinando Sua Produtividade</a> <small>(tb. T2)</small></td>
<td style="text-align: center;">13705 / 3109.12</td>
<td style="text-align: center;">16h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/ia-muito-alem-do-prompt/index.html">IA — Muito Além do Prompt</a> <small>(tb. T2)</small></td>
<td style="text-align: center;"><em>a cadastrar</em></td>
<td style="text-align: center;">24h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/apresentacoes-dinamicas-ia/index.html">Apresentações Dinâmicas com IA Generativa</a></td>
<td style="text-align: center;">14196 / 1745.51</td>
<td style="text-align: center;">32h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/ia-aplicada-avancada/index.html">IA Aplicada Avançada — Multiagent, RAG e LLM Ops</a></td>
<td style="text-align: center;">NC-04</td>
<td style="text-align: center;">80h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="even">
<td><a href="./cursos/ai-901-azure/index.html">AI-900 — IA com Azure</a></td>
<td style="text-align: center;">13674 / 283.97</td>
<td style="text-align: center;">48h</td>
<td style="text-align: center;"><span class="status-pill status-futuro">futuro</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
</tbody>
</table>
</section>
<section id="trilha-2-dados" class="level4">
<h4 class="anchored" data-anchor-id="trilha-2-dados">Trilha 2 — Dados</h4>
<table class="caption-top table">
<caption>Trilha 2 — Dados.</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Curso</th>
<th style="text-align: center;">Código</th>
<th style="text-align: center;">CH</th>
<th style="text-align: center;">Status</th>
<th style="text-align: center;">Material</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./cursos/informatica-fundamental-ia/index.html">Informática Fundamental com IA</a> <small>(tb. T6)</small></td>
<td style="text-align: center;">14193 / 286.90</td>
<td style="text-align: center;">60h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/excel-com-ia/index.html">Excel com IA</a> <small>(tb. T6)</small></td>
<td style="text-align: center;">14192 / 391.2</td>
<td style="text-align: center;">28h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/excel-avancado-ia/index.html">Excel Avançado com IA — Automação e Dados</a> <small>(tb. T6)</small></td>
<td style="text-align: center;">14191 / 391.19</td>
<td style="text-align: center;">36h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/excel-dashboard/index.html">Excel Dashboard — Planilhas Gerenciais</a> <small>(tb. T6)</small></td>
<td style="text-align: center;">12940 / 391.114</td>
<td style="text-align: center;">24h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/power-bi/index.html">Power BI</a></td>
<td style="text-align: center;">13675 / 1745.8</td>
<td style="text-align: center;">60h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/sql-para-dados/index.html">SQL para Dados</a></td>
<td style="text-align: center;">NC-02</td>
<td style="text-align: center;">60h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="odd">
<td><a href="./cursos/fundamentos-engenharia-dados/index.html">Fundamentos de Engenharia de Dados</a></td>
<td style="text-align: center;">NC-03</td>
<td style="text-align: center;">120h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="even">
<td><a href="./cursos/banco-de-dados/index.html">Banco de Dados</a></td>
<td style="text-align: center;">13616 / 986.65</td>
<td style="text-align: center;">120h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/ia-generativa-negocios/index.html">IA Generativa Aplicada a Negócios</a> <small>(tb. T5)</small></td>
<td style="text-align: center;">NC-01</td>
<td style="text-align: center;">24h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="even">
<td><a href="./cursos/analista-dados-big-data/index.html">Analista de Dados — Big Data Science</a></td>
<td style="text-align: center;">13455 / 984.44</td>
<td style="text-align: center;">120h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/data-intelligence/index.html">Data Intelligence — ETL, ML e Microsoft Fabric</a></td>
<td style="text-align: center;">13681 / 984.56</td>
<td style="text-align: center;">216h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
</tbody>
</table>
</section>
<section id="trilha-3-infraestrutura-cloud-e-redes" class="level4">
<h4 class="anchored" data-anchor-id="trilha-3-infraestrutura-cloud-e-redes">Trilha 3 — Infraestrutura, Cloud e Redes</h4>
<table class="caption-top table">
<caption>Trilha 3 — Infraestrutura, Cloud e Redes.</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Curso</th>
<th style="text-align: center;">Código</th>
<th style="text-align: center;">CH</th>
<th style="text-align: center;">Status</th>
<th style="text-align: center;">Material</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./cursos/linux-profissionais-ti/index.html">Linux para Profissionais de TI</a></td>
<td style="text-align: center;">NC-07</td>
<td style="text-align: center;">40h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="even">
<td><a href="./cursos/cloud-fundamentos-azure/index.html">Cloud Fundamentos com Azure</a></td>
<td style="text-align: center;">NC-08</td>
<td style="text-align: center;">40h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="odd">
<td><a href="./cursos/containers-kubernetes/index.html">Containers e Kubernetes Essentials</a></td>
<td style="text-align: center;">NC-09</td>
<td style="text-align: center;">60h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="even">
<td><a href="./cursos/google-cloud-foundations/index.html">Google Cloud Foundations</a></td>
<td style="text-align: center;">13188 / 286.220</td>
<td style="text-align: center;">72h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/cisco-ccna/index.html">Formação Cisco CCNA V7.0</a></td>
<td style="text-align: center;">13191 / 286.174</td>
<td style="text-align: center;">210h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/aws-restart/index.html">AWS RE/START</a></td>
<td style="text-align: center;">13339 / 286.227</td>
<td style="text-align: center;">460h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/formacao-infra-redes/index.html">Formação Infra e Redes</a></td>
<td style="text-align: center;">12935 / 992.32</td>
<td style="text-align: center;">332h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
</tbody>
</table>
</section>
<section id="trilha-4-cibersegurança" class="level4">
<h4 class="anchored" data-anchor-id="trilha-4-cibersegurança">Trilha 4 — Cibersegurança</h4>
<table class="caption-top table">
<caption>Trilha 4 — Cibersegurança.</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Curso</th>
<th style="text-align: center;">Código</th>
<th style="text-align: center;">CH</th>
<th style="text-align: center;">Status</th>
<th style="text-align: center;">Material</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./cursos/lgpd-governanca-dados/index.html">LGPD e Governança de Dados</a></td>
<td style="text-align: center;">NC-05</td>
<td style="text-align: center;">24h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="even">
<td><a href="./cursos/pentest-fundamentos/index.html">Pentest Fundamentos</a></td>
<td style="text-align: center;">NC-06</td>
<td style="text-align: center;">60h</td>
<td style="text-align: center;"><span class="status-pill status-novo">novo</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
<tr class="odd">
<td><a href="./cursos/ciberseguranca-cisco/index.html">Cibersegurança Cisco</a></td>
<td style="text-align: center;">13189 / 286.219</td>
<td style="text-align: center;">100h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
</tbody>
</table>
</section>
<section id="trilha-5-programação-e-desenvolvimento" class="level4">
<h4 class="anchored" data-anchor-id="trilha-5-programação-e-desenvolvimento">Trilha 5 — Programação e Desenvolvimento</h4>
<table class="caption-top table">
<caption>Trilha 5 — Programação e Desenvolvimento.</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Curso</th>
<th style="text-align: center;">Código</th>
<th style="text-align: center;">CH</th>
<th style="text-align: center;">Status</th>
<th style="text-align: center;">Material</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./cursos/programador-front-end-ia/index.html">Programador Front-End com IA</a></td>
<td style="text-align: center;">13613 / 986.81</td>
<td style="text-align: center;">80h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/mobile-react-native/index.html">Programação Mobile — React Native</a></td>
<td style="text-align: center;">13190 / 986.101</td>
<td style="text-align: center;">60h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/back-end-java/index.html">Desenvolvedor Back-End Java</a></td>
<td style="text-align: center;">12897 / 986.94</td>
<td style="text-align: center;">84h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/python-avancado-ia/index.html">Programação Avançada em Python com IA</a></td>
<td style="text-align: center;">14195</td>
<td style="text-align: center;">100h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/python-django/index.html">Programação em Python com Django</a></td>
<td style="text-align: center;">12953 / 986.97</td>
<td style="text-align: center;">168h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/php-laravel/index.html">Programação em PHP com Laravel</a></td>
<td style="text-align: center;">12952 / 986.39</td>
<td style="text-align: center;">168h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/full-stack-java/index.html">Programador Full Stack — Formação com Java</a></td>
<td style="text-align: center;">13323 / 986.82</td>
<td style="text-align: center;">360h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/back-end-dotnet/index.html">Desenvolvedor Back-End .NET</a></td>
<td style="text-align: center;">12896 / 986.95</td>
<td style="text-align: center;">84h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/full-stack-dotnet/index.html">Programador Full Stack com Microsoft .NET</a></td>
<td style="text-align: center;">13343 / 283.103</td>
<td style="text-align: center;">360h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/programacao-node/index.html">Programação NODE</a></td>
<td style="text-align: center;">—</td>
<td style="text-align: center;">100h</td>
<td style="text-align: center;"><span class="status-pill status-futuro">futuro</span></td>
<td style="text-align: center;">estrutura</td>
</tr>
</tbody>
</table>
</section>
<section id="trilha-6-produtividade-e-citizen-development" class="level4">
<h4 class="anchored" data-anchor-id="trilha-6-produtividade-e-citizen-development">Trilha 6 — Produtividade e Citizen Development</h4>
<table class="caption-top table">
<caption>Trilha 6 — Produtividade e Citizen Development.</caption>
<colgroup>
<col style="width: 46%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Curso</th>
<th style="text-align: center;">Código</th>
<th style="text-align: center;">CH</th>
<th style="text-align: center;">Status</th>
<th style="text-align: center;">Material</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="./cursos/excel-com-ia-fundamentos/index.html">Excel com IA — Fundamentos</a></td>
<td style="text-align: center;">14758 / 991.50</td>
<td style="text-align: center;">8h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/power-platform/index.html">Microsoft Power Platform</a></td>
<td style="text-align: center;">13192 / 1746.48</td>
<td style="text-align: center;">48h</td>
<td style="text-align: center;"><span class="status-pill status-retorno">retorno</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="odd">
<td><a href="./cursos/informatica-melhor-idade/index.html">Informática Básica para Melhor Idade</a></td>
<td style="text-align: center;">12700 / 392.3</td>
<td style="text-align: center;">60h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
<tr class="even">
<td><a href="./cursos/smartphone-uso-seguro/index.html">Smartphone — Uso Eficiente e Seguro</a></td>
<td style="text-align: center;">a cadastrar / 1746.68</td>
<td style="text-align: center;">16h</td>
<td style="text-align: center;"><span class="status-pill status-ativo">ativo</span></td>
<td style="text-align: center;">✅ publicado</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>Código</strong> no formato <strong>SENAC RJ (SGA) / DN</strong> para cursos já cadastrados, ou <strong>NC-xx</strong> para os cursos novos (propostas a validar no GT Tech). Cursos que aparecem em mais de uma trilha estão listados na trilha principal, com a marca <em>(tb. Tn)</em>.</p>
</blockquote>
</section>
</section>
<section id="as-6-trilhas" class="level2">
<h2 class="anchored" data-anchor-id="as-6-trilhas">As 6 trilhas</h2>
<div class="grade-cards">
<section id="ia-aplicada" class="level3 card-trilha">
<h3 class="anchored" data-anchor-id="ia-aplicada"><a href="./trilhas/trilha-1-ia-aplicada.html">1 — IA Aplicada</a></h3>
<p><span class="meta">Da produtividade pessoal com IA até IA aplicada profissionalmente.</span></p>
</section>
<section id="dados" class="level3 card-trilha">
<h3 class="anchored" data-anchor-id="dados"><a href="./trilhas/trilha-2-dados.html">2 — Dados</a></h3>
<p><span class="meta">Do aluno-base a Analista de Dados (2A) e Engenheiro de Dados (2B).</span></p>
</section>
<section id="infraestrutura-cloud-e-redes" class="level3 card-trilha">
<h3 class="anchored" data-anchor-id="infraestrutura-cloud-e-redes"><a href="./trilhas/trilha-3-infraestrutura.html">3 — Infraestrutura, Cloud e Redes</a></h3>
<p><span class="meta">Da TI tradicional ao cloud native (AWS, Azure, GCP, Kubernetes).</span></p>
</section>
<section id="cibersegurança" class="level3 card-trilha">
<h3 class="anchored" data-anchor-id="cibersegurança"><a href="./trilhas/trilha-4-ciberseguranca.html">4 — Cibersegurança</a></h3>
<p><span class="meta">Governança, defesa e ofensiva — da LGPD ao Pentest.</span></p>
</section>
<section id="programação-e-desenvolvimento" class="level3 card-trilha">
<h3 class="anchored" data-anchor-id="programação-e-desenvolvimento"><a href="./trilhas/trilha-5-programacao.html">5 — Programação e Desenvolvimento</a></h3>
<p><span class="meta">Da primeira linguagem ao Full Stack, com pontes para Dados e IA.</span></p>
</section>
<section id="produtividade-e-citizen-development" class="level3 card-trilha">
<h3 class="anchored" data-anchor-id="produtividade-e-citizen-development"><a href="./trilhas/trilha-6-produtividade.html">6 — Produtividade e Citizen Development</a></h3>
<p><span class="meta">Excel, Power Platform e inclusão digital para o público não-técnico.</span></p>
</section>
</div>
</section>
<section id="como-usar-este-repositório" class="level2">
<h2 class="anchored" data-anchor-id="como-usar-este-repositório">Como usar este repositório</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Se você é…</th>
<th>Comece por…</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Instrutor de um curso</strong></td>
<td>A página do seu curso (busca no topo ou pela trilha). Lá estão PC, PTD, referências e materiais de apoio.</td>
</tr>
<tr class="even">
<td><strong>Coordenação / GT Tech</strong></td>
<td>O <a href="./fluxograma.html">Fluxograma das trilhas</a> e as páginas de trilha, para enxergar lacunas e progressão.</td>
</tr>
<tr class="odd">
<td><strong>Quem vai criar/atualizar curso</strong></td>
<td>O guia <strong><a href="./como-atualizar.html">Como atualizar</a></strong> — gabarito-padrão, scaffolder e regras de versionamento.</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Sobre o status do material.</strong> Cada curso exibe um selo: <span class="status-pill status-ativo">ativo</span> (no catálogo), <span class="status-pill status-novo">novo</span> (proposta a validar no GT Tech), <span class="status-pill status-retorno">retorno</span> (em atualização para voltar) e <span class="status-pill status-futuro">futuro</span> (horizonte de expansão). As trilhas e os cursos novos (NC-01…NC-09) são <strong>propostas em validação</strong> — não decisões consolidadas.</p>
</div>
</div>
</section>
<section id="convenções" class="level2">
<h2 class="anchored" data-anchor-id="convenções">Convenções</h2>
<ul>
<li><strong>Idioma:</strong> português do Brasil.</li>
<li><strong>Fonte canônica do PC/PTD:</strong> os arquivos oficiais (<code>.docx</code>) ficam linkados em cada curso; este repositório é a <strong>camada navegável e versionada</strong> por cima deles.</li>
<li><strong>Toda alteração relevante</strong> entra no <strong><a href="./changelog.html">Changelog</a></strong> e no histórico da própria página do curso.</li>
</ul>
<hr>
<p><em>Mantido pela Cápsula de Inovação — Coordenação de Tecnologias, SENAC RJ. Documento vivo, atualizado conforme o portfólio evolui.</em></p>


<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Status:</strong> <span class="status-pill status-futuro">futuro</span> &nbsp; futuro — horizonte de expansão &nbsp;·&nbsp; <strong>Código:</strong> SGA 13674 / DN 283.97 &nbsp;·&nbsp; <strong>Carga horária:</strong> 48h &nbsp;·&nbsp; <strong>Tipo:</strong> Aperfeiçoamento · Presencial ou Remoto</p>
<p><strong>Material:</strong> completo &nbsp;·&nbsp; <strong>Última atualização:</strong> 2026-06-23</p>
</div>
</div>
</div>
</section>
<section id="onde-este-curso-entra-nas-trilhas" class="level2">
<h2 class="anchored" data-anchor-id="onde-este-curso-entra-nas-trilhas">Onde este curso entra nas trilhas</h2>
<p>Faz parte de: <a href="../../trilhas/trilha-1-ia-aplicada.qmd">Trilha 1 — IA Aplicada</a>.</p>
<blockquote class="blockquote">
<p><strong>Vem de:</strong> trilha de fundamentos de IA (porta consciente) · <strong>Próximo passo:</strong> aprofundamento em serviços de nuvem e certificação Microsoft Azure. Conecta com a <a href="../../trilhas/trilha-2-dados.qmd">Trilha Dados</a> via aprendizado de máquina (Azure ML Studio).</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Decisão a validar:</strong> o rótulo da página é “AI-901”, mas o curso oficial é <strong>Inteligência Artificial com Azure</strong> (SGA 13674, DN 283.97) e o PC prepara o aluno para o exame <strong>AI-900 — Azure AI Fundamentals</strong> (não “AI-901”). Avaliar no GT Tech se o título/slug da página deve ser ajustado para o nome/código oficiais ou para o exame correto (AI-900).</p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-1-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-1" role="tab" aria-controls="tabset-1-1" aria-selected="true" href="">PC — Plano de Curso</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-2" role="tab" aria-controls="tabset-1-2" aria-selected="false" href="">PTD — Plano de Trabalho Docente</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-3" role="tab" aria-controls="tabset-1-3" aria-selected="false" href="">Referências Bibliográficas</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-1-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-1-4" role="tab" aria-controls="tabset-1-4" aria-selected="false" href="">Materiais Complementares</a></li></ul>
<div class="tab-content">
<div id="tabset-1-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-1-1-tab">
<p><strong>Fonte oficial:</strong> <a href="fonte/PC - IA com Azure.docx">PC — IA com Azure (.docx)</a></p>
<section id="identificação" class="level3">
<h3 class="anchored" data-anchor-id="identificação">1. Identificação</h3>
<ul>
<li><strong>Eixo:</strong> Informação e Comunicação · <strong>Segmento:</strong> Tecnologia da Informação</li>
<li><strong>Tipo:</strong> Aperfeiçoamento · <strong>Carga horária:</strong> 48 horas · <strong>Formato:</strong> Presencial ou Remoto</li>
<li><strong>Código DN:</strong> 283.97 · <strong>Código Senac RJ (SGA):</strong> 13674 · Ano-base: 2024</li>
</ul>
</section>
<section id="requisitos-de-acesso" class="level3">
<h3 class="anchored" data-anchor-id="requisitos-de-acesso">2. Requisitos de acesso</h3>
<ul>
<li>Idade mínima: 18 anos.</li>
<li>Requisitos específicos: <strong>Ensino médio completo</strong>, <strong>Excel avançado</strong> e conhecimentos em ferramentas de <strong>IA generativa</strong>.</li>
<li>Documentos: identidade, CPF, comprovante ou autodeclaração do conhecimento específico.</li>
</ul>
</section>
<section id="justificativa" class="level3">
<h3 class="anchored" data-anchor-id="justificativa">3. Justificativa</h3>
<p>A adoção de IA por micro, pequenas e médias empresas brasileiras saltou de 61% para 74% em um ano, e 47% já usam computação em nuvem. Mais da metade das empresas latino-americanas que usam IA registram retorno financeiro. Nesse cenário, dominar os serviços de IA do <strong>Microsoft Azure</strong> dá vantagem competitiva — automação de processos, melhores decisões e democratização do acesso a recursos avançados de TIC via plataforma integrada.</p>
</section>
<section id="objetivo" class="level3">
<h3 class="anchored" data-anchor-id="objetivo">4. Objetivo</h3>
<p>Subsidiar o participante na utilização dos serviços de <strong>Inteligência Artificial do Microsoft Azure</strong> para criar soluções e melhorar processos em diversas áreas. O curso <strong>prepara para o exame Microsoft Certified AI-900 — Azure AI Fundamentals</strong>.</p>
</section>
<section id="organização-curricular" class="level3">
<h3 class="anchored" data-anchor-id="organização-curricular">5. Organização curricular</h3>
<p><strong>Unidade Curricular única:</strong> Inteligência Artificial com Azure — 48h. <strong>Indicador:</strong> utiliza recursos e serviços da Azure para otimizar processos e tarefas conforme as características e comportamentos dos modelos de IA.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Elemento</th>
<th>Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Conhecimentos</strong></td>
<td>IA (conceitos e aplicações práticas); ética em IA (qualidade de dados, transparência, privacidade); visão geral dos serviços de IA da Azure; <strong>Azure Studio / OpenAI Studio</strong> (criação de recursos, configuração de agente de IA); conceitos básicos de aprendizado de máquina; criação e gerenciamento de máquina virtual; reconhecimento e classificação de imagens; manipulação de vídeos e imagens com IA; <strong>Azure Machine Learning Studio</strong> (ML sem código).</td>
</tr>
<tr class="even">
<td><strong>Habilidades</strong></td>
<td>Diferenciar tipos de serviços de IA conforme as demandas da empresa; construir sistemas com IA para otimizar processos do negócio.</td>
</tr>
<tr class="odd">
<td><strong>Atitudes/Valores</strong></td>
<td>Ética na configuração de serviços de IA; responsabilidade no uso de recursos computacionais; atenção à segurança e à privacidade.</td>
</tr>
</tbody>
</table>
</section>
<section id="orientações-metodológicas" class="level3">
<h3 class="anchored" data-anchor-id="orientações-metodológicas">6. Orientações metodológicas</h3>
<p>Prática pedagógica contextualizada (aprendizagem com autonomia, conforme a Proposta Pedagógica do Senac): simulação de situações-problema com dados reais e estudos de caso para construir cenários de uso dos serviços de IA da Azure. Reforça as marcas formativas Senac (domínio técnico-científico, visão crítica, atitude sustentável, autonomia digital).</p>
</section>
<section id="avaliação" class="level3">
<h3 class="anchored" data-anchor-id="avaliação">7. Avaliação</h3>
<p>Menções de processo <strong>Atendido (A) / Parcialmente atendido (PA) / Não atendido (NA)</strong> e, ao final, <strong>A / NA</strong> por indicador. Resultado final: <strong>Concluiu (C)</strong> com indicadores atendidos e frequência <strong>≥ 75%</strong>; <strong>Não concluiu (NC)</strong> caso contrário. Recuperação contínua ao longo do processo.</p>
</section>
<section id="recursos-perfil-e-certificação" class="level3">
<h3 class="anchored" data-anchor-id="recursos-perfil-e-certificação">8–11. Recursos, perfil e certificação</h3>
<p>Estação por aluno (Intel Core i5 10ª geração+, Windows 10 Pro 64-bit, 8 GB RAM, SSD 256 GB, monitor 21”+) e acesso à plataforma <a href="https://azure.microsoft.com" class="uri">https://azure.microsoft.com</a>. Sem material físico ao estudante. Docente com experiência em desenvolvimento de sistemas e nas ferramentas de IA do Azure, formação em TI ou correlata; <strong>desejável certificação Microsoft Azure AI-900</strong>. Certificado de <strong>Aperfeiçoamento em Inteligência Artificial com Azure</strong>, chancelado também pela Microsoft, validade nacional.</p>
</section>
</div>
<div id="tabset-1-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-2-tab">
<p><strong>Fonte oficial:</strong> <a href="fonte/PTD - IA com Azure.docx">PTD — IA com Azure (.docx)</a></p>
<p><strong>Situação de aprendizagem — Mercado SuperBom.</strong> Um mercado de bairro em crescimento busca IA para automatizar o controle de estoque, ajustar preços em tempo real e personalizar a interação com clientes. Ao longo das 48h, a turma: (1) <strong>treina e publica um modelo de identificação de produtos em prateleira</strong> na Azure, simulando a integração com o sistema de reposição de estoque; e (2) <strong>implementa um chatbot</strong> com o <strong>Azure Bot Service</strong>, integrando-o a um canal de comunicação (site do mercado) com apoio de IA generativa (ChatGPT, Gemini, Copilot, Claude, DeepSeek).</p>
<p><strong>Indicador da UC:</strong> utiliza recursos e serviços da Azure para otimizar processos e tarefas conforme as características e comportamentos dos modelos de IA.</p>
<section id="orientações-operacionais-recorrentes" class="level3">
<h3 class="anchored" data-anchor-id="orientações-operacionais-recorrentes">Orientações operacionais (recorrentes)</h3>
<ul>
<li>Usar <strong>Microsoft Edge</strong> em todas as aulas — evita bugs no portal Azure.</li>
<li>Orientar sobre o <strong>uso correto dos créditos Azure</strong> da conta aluno do SENAC: não usar recursos fora do escopo e <strong>desativar os recursos ao fim de cada aula</strong>.</li>
<li>Garantir a conta de estudante (<strong>azure.microsoft.com/pt-br/free/students</strong>) e o acesso ao <strong>Campus Digital</strong> (primeiroacesso.rj.senac.br); anotar e-mail e senha, necessários para acessar a Azure.</li>
<li>Registrar as etapas de desenvolvimento e justificar as configurações em <strong>documento colaborativo</strong>.</li>
</ul>
</section>
<section id="planejamento-das-aulas-sequência-sugerida" class="level3">
<h3 class="anchored" data-anchor-id="planejamento-das-aulas-sequência-sugerida">Planejamento das aulas (sequência sugerida)</h3>
<p>A UC é desenvolvida em encontros que partem da apresentação e dos conceitos/ética de IA, avançam por <strong>Azure Studio / OpenAI Studio</strong> (criação de recursos e agentes), <strong>máquinas virtuais</strong>, <strong>visão computacional</strong> (reconhecimento e classificação de imagens, manipulação de vídeos/imagens) e <strong>aprendizado de máquina sem código no Azure ML Studio</strong>, convergindo para a entrega do caso SuperBom (modelo de prateleira + chatbot). A primeira aula faz o levantamento de perfil da turma (quem já é da área de TI / programação) para flexibilizar o planejamento.</p>
</section>
<section id="avaliação-procedimentos-e-instrumentos" class="level3">
<h3 class="anchored" data-anchor-id="avaliação-procedimentos-e-instrumentos">Avaliação (procedimentos e instrumentos)</h3>
<p>Avaliação <strong>individual e em grupo, gradual e contínua</strong>. Procedimentos: atividades práticas com os recursos e serviços da Azure. Instrumentos: atividades práticas e apresentação dos resultados (individuais ou em grupo) usando os recursos de IA da Azure.</p>
</section>
</div>
<div id="tabset-1-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-3-tab">
<p><strong>Básica (oficial — do PC)</strong></p>
<ul>
<li>O PC não indica bibliografia básica (“Não há”). A referência operacional é a documentação da plataforma: <strong>Microsoft Azure</strong> — <a href="https://azure.microsoft.com" class="uri">https://azure.microsoft.com</a>.</li>
</ul>
<p><strong>Complementar (apoio — fontes citadas na Justificativa do PC)</strong></p>
<ul>
<li>“IA: 74% das MPMEs utilizam como estratégia de produtividade” (Valor Econômico / Dino, 2024).</li>
<li>“IA em micro, pequenas e médias empresas: tendências, desafios e oportunidades” (Microsoft / Edelman, 2024).</li>
<li>Caso CASSI — análise de autorizações médicas com IA do Microsoft Azure (Microsoft News Brasil).</li>
<li>Ferramentas de IA generativa para apoio em aula: ChatGPT, Gemini, Copilot, Claude, DeepSeek.</li>
</ul>
</div>
<div id="tabset-1-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-1-4-tab">
<ul>
<li><strong>PC — IA com Azure (.docx):</strong> <a href="fonte/PC - IA com Azure.docx">PC - IA com Azure.docx</a> — Plano de Curso oficial (SGA 13674).</li>
<li><strong>PTD — IA com Azure (.docx):</strong> <a href="fonte/PTD - IA com Azure.docx">PTD - IA com Azure.docx</a> — Plano de Trabalho Docente (caso SuperBom, aula a aula).</li>
<li><strong>Ementa — IA com Azure (.docx):</strong> <a href="fonte/Ementa - IA com Azure.docx">Ementa - IA com Azure.docx</a> — ementa do curso 13674.</li>
<li>Demais apoios na pasta de origem (SharePoint): autodeclaração de requisito, simulados, vídeo comercial, precificação e fichas de turma — não versionados aqui.</li>
</ul>
</div>
</div>
</div>
</section>
<section id="histórico-de-atualizações-deste-curso" class="level2">
<h2 class="anchored" data-anchor-id="histórico-de-atualizações-deste-curso">Histórico de atualizações (deste curso)</h2>
<table class="caption-top table">
<caption>Histórico do material deste curso.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 62%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Data</th>
<th>O que mudou</th>
<th>Autor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026-06-23</td>
<td>Página preenchida com PC, PTD e materiais a partir dos arquivos oficiais (SharePoint). Registrada divergência de rótulo: página “AI-901” vs.&nbsp;curso oficial “IA com Azure” (SGA 13674) preparando para o exame AI-900.</td>
<td>Cápsula de Inovação</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Status:</strong> <span class="status-pill status-ativo">ativo</span> &nbsp; ativo no catálogo · Código: SGA 13188 / DN 286.220 &nbsp;·&nbsp; <strong>Carga horária:</strong> 72h (UC1 32h + UC2 40h) &nbsp;·&nbsp; <strong>Tipo:</strong> Aperfeiçoamento · Presencial ou Remoto</p>
<p><strong>Material:</strong> completo &nbsp;·&nbsp; <strong>Última atualização:</strong> 2026-06-23</p>
</div>
</div>
</div>
</section>
<section id="onde-este-curso-entra-nas-trilhas-1" class="level2">
<h2 class="anchored" data-anchor-id="onde-este-curso-entra-nas-trilhas-1">Onde este curso entra nas trilhas</h2>
<p>Faz parte de: <a href="../../trilhas/trilha-3-infraestrutura.qmd">Trilha 3 — Infraestrutura, Cloud e Redes</a>.</p>
<blockquote class="blockquote">
<p><em>Preencha aqui o pré-requisito (curso anterior) e o próximo passo (call-to-action de upsell), conforme o diagrama da trilha. Ex.: “Vem de <strong>X</strong> · Próximo passo: <strong>Y</strong>”.</em></p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-2-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-1" role="tab" aria-controls="tabset-2-1" aria-selected="true" href="">PC — Plano de Curso</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-2" role="tab" aria-controls="tabset-2-2" aria-selected="false" href="">PTD — Plano de Trabalho Docente</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-3" role="tab" aria-controls="tabset-2-3" aria-selected="false" href="">Referências Bibliográficas</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-2-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-2-4" role="tab" aria-controls="tabset-2-4" aria-selected="false" href="">Materiais Complementares</a></li></ul>
<div class="tab-content">
<div id="tabset-2-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-2-1-tab">
<p><strong>Fonte oficial:</strong> <a href="fonte/PC - Google Cloud Foundations.docx">PC — Google Cloud Foundations (.docx)</a></p>
<section id="identificação-1" class="level3">
<h3 class="anchored" data-anchor-id="identificação-1">1. Identificação</h3>
<ul>
<li><strong>Título:</strong> Google Cloud Foundations · <strong>Eixo:</strong> Informação e Comunicação · <strong>Segmento:</strong> Tecnologia da Informação</li>
<li><strong>Tipo:</strong> Aperfeiçoamento · <strong>Carga horária:</strong> 72 horas · <strong>Código DN:</strong> 286.220 · <strong>Código Senac RJ:</strong> 13188</li>
</ul>
</section>
<section id="requisitos-de-acesso-1" class="level3">
<h3 class="anchored" data-anchor-id="requisitos-de-acesso-1">2. Requisitos de acesso</h3>
<ul>
<li>Idade mínima: 16 anos · Escolaridade: não há.</li>
<li>Conhecimentos básicos de informática (sistema operacional, pacote Office, navegação na internet). <strong>Desejável inglês técnico.</strong></li>
<li>Documentos: identidade, CPF, autodeclaração de conhecimentos básicos de informática.</li>
</ul>
</section>
<section id="justificativa-1" class="level3">
<h3 class="anchored" data-anchor-id="justificativa-1">3. Justificativa</h3>
<p>Com a globalização e a internet, cresce a necessidade de acessar aplicativos, dados e recursos de qualquer lugar. Habilidades em <strong>computação em nuvem</strong> são cada vez mais demandadas. A Brasscom estima demanda de <strong>797 mil talentos de TI (2021–2025)</strong> e déficit anual de 106 mil profissionais — o que reforça a urgência da formação na área.</p>
</section>
<section id="objetivo-1" class="level3">
<h3 class="anchored" data-anchor-id="objetivo-1">4. Objetivo</h3>
<p>Fornecer os <strong>conceitos e serviços fundamentais em nuvem da plataforma Google Cloud</strong>, habilitando o profissional a incluir e gerenciar diferentes modelos de serviço (<strong>IaaS, PaaS, SaaS</strong>) e padrões de conectividade e segurança em nuvem.</p>
</section>
<section id="organização-curricular-1" class="level3">
<h3 class="anchored" data-anchor-id="organização-curricular-1">5. Organização curricular</h3>
<p>Duas unidades curriculares, 72h no total:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 83%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Unidade Curricular</th>
<th style="text-align: right;">CH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>UC1</strong> — Operar e Configurar Redes de Dispositivos utilizando Sistemas Linux</td>
<td style="text-align: right;">32h</td>
</tr>
<tr class="even">
<td><strong>UC2</strong> — Configurar e Administrar Serviços Fundamentais do Google Cloud Platform</td>
<td style="text-align: right;">40h</td>
</tr>
</tbody>
</table>
<p><strong>UC1 — Redes e Linux</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Elemento</th>
<th>Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Conhecimentos</strong></td>
<td>Redes de computadores; endereçamento IP e sub-redes; protocolos TCP/UDP/ICMP; distribuições Linux; instalação e configuração (IP, Gateway, Máscara, DHCP, DNS, Apache, Samba); lógica de programação <strong>Bash</strong>; comandos essenciais de terminal; gerenciamento de serviços e processos; <strong>firewall (iptables/firewalld)</strong>; compartilhamento de dados em rede; controle de acesso; <strong>acesso remoto SSH</strong>; backup e agendamento.</td>
</tr>
<tr class="even">
<td><strong>Habilidades</strong></td>
<td>Testar conectividade e interfaceamento de rede; manipular o SO Linux; gerenciar acesso e permissões; usar termos técnicos nas rotinas.</td>
</tr>
<tr class="odd">
<td><strong>Atitudes/Valores</strong></td>
<td>Colaboração; sigilo no tratamento de dados; postura profissional; zelo pelos equipamentos.</td>
</tr>
</tbody>
</table>
<p><strong>UC2 — Google Cloud Platform</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Elemento</th>
<th>Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Conhecimentos</strong></td>
<td>Fundamentos de computação em nuvem e benefícios do GCP; arquitetura e serviços do GCP; <strong>serviços de computação</strong> (implementação e gerenciamento); configuração de <strong>redes virtuais</strong>; <strong>gerenciamento de identidades e controle de acesso (IAM)</strong>; práticas de segurança e monitoramento.</td>
</tr>
<tr class="even">
<td><strong>Habilidades</strong></td>
<td>Configurar redes virtuais, instâncias de VM e armazenamento no GCP; gerenciar identidades e controles de acesso; configurar e usar serviços de segurança.</td>
</tr>
<tr class="odd">
<td><strong>Atitudes/Valores</strong></td>
<td>Iniciativa para resolver problemas técnicos; colaboração; sigilo; postura profissional; zelo pelos equipamentos.</td>
</tr>
</tbody>
</table>
</section>
<section id="orientações-metodológicas-1" class="level3">
<h3 class="anchored" data-anchor-id="orientações-metodológicas-1">6. Orientações metodológicas</h3>
<p>Metodologia Senac de desenvolvimento de competências, com prática contextualizada. Na <strong>UC1</strong>, usar <strong>software de virtualização</strong> (VirtualBox) para instalação e priorizar o <strong>terminal</strong> nas atividades, preparando para a UC2. Na <strong>UC2</strong>, praticar em máquinas compatíveis com as ferramentas Google, com atividades online dentro da <strong>plataforma Google Cloud</strong> — verificar o acesso já na primeira aula.</p>
</section>
<section id="avaliação-1" class="level3">
<h3 class="anchored" data-anchor-id="avaliação-1">7. Avaliação</h3>
<p>Menções por indicador (<strong>Atendido / Parcialmente atendido / Não atendido</strong>) e por UC (<strong>Desenvolvida — D / Não desenvolvida — ND</strong>). Aprovação exige <strong>D em todas as UCs</strong> e <strong>frequência mínima de 75%</strong> (na EAD, pela realização das atividades). Recuperação imediata à constatação de dificuldades.</p>
</section>
<section id="recursos-perfil-e-certificação-1" class="level3">
<h3 class="anchored" data-anchor-id="recursos-perfil-e-certificação-1">8–10. Recursos, perfil e certificação</h3>
<p>1 computador por aluno (i5 10ª geração+, Windows 10+, 8GB RAM, internet 25Mb), com Chrome/Firefox/Edge, Office 365, <strong>VirtualBox</strong> e <strong>Packet Tracer</strong>; laboratório com internet. Docente com experiência em <strong>Linux e administração de nuvem</strong>, com a formação Google Cloud Foundations concluída e graduação/pós em TI ou afins. Certificado de <strong>aperfeiçoamento em Google Cloud Foundations</strong>, dupla chancela e validade nacional.</p>
</section>
</div>
<div id="tabset-2-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-2-tab">
<p><strong>Fontes oficiais:</strong> <a href="fonte/PTD - Google Cloud Foundations - UC1.docx">PTD — UC1 (.docx)</a> &nbsp;·&nbsp; <a href="fonte/PTD - Google Cloud Foundations - UC2.docx">PTD — UC2 (validado) (.docx)</a></p>
<p>O percurso é organizado em <strong>situações de aprendizagem</strong> baseadas em desafios de empresa, com avaliação por indicadores.</p>
<section id="uc1-operar-e-configurar-redes-linux-32h" class="level3">
<h3 class="anchored" data-anchor-id="uc1-operar-e-configurar-redes-linux-32h">UC1 — Operar e configurar redes Linux (32h)</h3>
<p><strong>Situação de aprendizagem:</strong> o aluno é recém-contratado pela empresa fictícia <strong>OMEGA PRIMUS</strong> e designado para implementar uma <strong>infraestrutura baseada em servidores Linux</strong> que otimize recursos. O trabalho percorre duas etapas — <strong>(1) configuração de redes</strong> e <strong>(2) instalação e configuração do sistema Linux em rede</strong> — com entrega final do <strong>desktop do usuário configurado</strong> conforme as premissas da empresa. Avaliação por instalação/configuração de Linux em rede e compartilhamento seguro de dados (máquina virtual no VirtualBox).</p>
</section>
<section id="uc2-serviços-fundamentais-do-google-cloud-40h" class="level3">
<h3 class="anchored" data-anchor-id="uc2-serviços-fundamentais-do-google-cloud-40h">UC2 — Serviços fundamentais do Google Cloud (40h)</h3>
<p><strong>Situação de aprendizagem:</strong> treinamento de <strong>migração da infraestrutura local para a nuvem Google</strong>, culminando na <strong>implementação de uma aplicação web no Google Cloud Platform</strong> com os principais serviços e recursos da plataforma. O instrutor apresenta visão geral do GCP, conduz a definição de requisitos em grupo (funcionalidades, armazenamento, banco de dados, pontos de entrada) e orienta laboratórios práticos na plataforma do parceiro Google Cloud.</p>
</section>
</div>
<div id="tabset-2-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-3-tab">
<p><strong>Básica (oficial — do PC)</strong></p>
<ul>
<li><strong>UC1:</strong> SANTOS, Ederson Cruz Marques dos. <em>Sistema Operacional II</em>. São Paulo: Editora Senac São Paulo, 2021. 159 p.</li>
<li><strong>UC2:</strong> FERREIRA, Haroldo da Silva. <em>Soluções de Cloud Computing</em>. São Paulo: Editora Senac São Paulo, 2022.</li>
</ul>
<p><strong>Complementar (do PC)</strong></p>
<ul>
<li>SANTOS, Marcelo Henrique dos. <em>Aplicações em Cloud Computing</em>. São Paulo: Editora Senac São Paulo, 2022. (Série Universitária).</li>
</ul>
</div>
<div id="tabset-2-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-2-4-tab">
<ul>
<li><strong>Plano de Curso (PC):</strong> <a href="fonte/PC - Google Cloud Foundations.docx">PC - Google Cloud Foundations.docx</a></li>
<li><strong>Plano de Trabalho Docente — UC1:</strong> <a href="fonte/PTD - Google Cloud Foundations - UC1.docx">PTD - Google Cloud Foundations - UC1.docx</a></li>
<li><strong>Plano de Trabalho Docente — UC2 (validado):</strong> <a href="fonte/PTD - Google Cloud Foundations - UC2.docx">PTD - Google Cloud Foundations - UC2.docx</a></li>
<li><strong>Ementa do curso:</strong> <a href="fonte/Ementa - Google Cloud Foundations.docx">Ementa - Google Cloud Foundations.docx</a></li>
<li><strong>Apoio na pasta de origem (SharePoint):</strong> termo unificado de aulas remotas, autodeclaração de matrícula, guia do curso, planilha de precificação e PPTs da UC1 (<code>13188.PTD.zip</code>).</li>
</ul>
</div>
</div>
</div>
</section>
<section id="histórico-de-atualizações-deste-curso-1" class="level2">
<h2 class="anchored" data-anchor-id="histórico-de-atualizações-deste-curso-1">Histórico de atualizações (deste curso)</h2>
<table class="caption-top table">
<caption>Histórico do material deste curso.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 62%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Data</th>
<th>O que mudou</th>
<th>Autor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026-06-23</td>
<td>Página preenchida com PC e materiais a partir dos arquivos oficiais (SharePoint).</td>
<td>Cápsula de Inovação</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p><strong>Status:</strong> <span class="status-pill status-ativo">ativo</span> &nbsp; ativo no catálogo · Código: SGA 13339 / DN 286.227 &nbsp;·&nbsp; <strong>Carga horária:</strong> 460h &nbsp;·&nbsp; <strong>Tipo:</strong> Aperfeiçoamento · Presencial · Origem: canal próprio — parceria AWS (sazonal)</p>
<p><strong>Material:</strong> completo &nbsp;·&nbsp; <strong>Última atualização:</strong> 2026-06-23</p>
</div>
</div>
</div>
</section>
<section id="onde-este-curso-entra-nas-trilhas-2" class="level2">
<h2 class="anchored" data-anchor-id="onde-este-curso-entra-nas-trilhas-2">Onde este curso entra nas trilhas</h2>
<p>Faz parte de: <a href="../../trilhas/trilha-3-infraestrutura.qmd">Trilha 3 — Infraestrutura, Cloud e Redes</a>.</p>
<blockquote class="blockquote">
<p><em>Preencha aqui o pré-requisito (curso anterior) e o próximo passo (call-to-action de upsell), conforme o diagrama da trilha. Ex.: “Vem de <strong>X</strong> · Próximo passo: <strong>Y</strong>”.</em></p>
</blockquote>
<div class="tabset-margin-container"></div><div class="panel-tabset">
<ul class="nav nav-tabs" role="tablist"><li class="nav-item" role="presentation"><a class="nav-link active" id="tabset-3-1-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-1" role="tab" aria-controls="tabset-3-1" aria-selected="true" href="">PC — Plano de Curso</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-2-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-2" role="tab" aria-controls="tabset-3-2" aria-selected="false" href="">PTD — Plano de Trabalho Docente</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-3-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-3" role="tab" aria-controls="tabset-3-3" aria-selected="false" href="">Referências Bibliográficas</a></li><li class="nav-item" role="presentation"><a class="nav-link" id="tabset-3-4-tab" data-bs-toggle="tab" data-bs-target="#tabset-3-4" role="tab" aria-controls="tabset-3-4" aria-selected="false" href="">Materiais Complementares</a></li></ul>
<div class="tab-content">
<div id="tabset-3-1" class="tab-pane active" role="tabpanel" aria-labelledby="tabset-3-1-tab">
<p><strong>Fonte oficial:</strong> <a href="fonte/PC - AWS ReStart.docx">PC — AWS ReStart (.docx)</a></p>
<blockquote class="blockquote">
<p><strong>Nota de carga horária:</strong> o PC oficial registra <strong>460h</strong> (Aperfeiçoamento, presencial). O subtítulo/catálogo menciona 400h — divergência a confirmar com a coordenação; aqui prevalece o PC.</p>
</blockquote>
<section id="identificação-2" class="level3">
<h3 class="anchored" data-anchor-id="identificação-2">1. Identificação</h3>
<ul>
<li><strong>Eixo:</strong> Informação e Comunicação · <strong>Segmento:</strong> Tecnologia da Informação</li>
<li><strong>Tipo:</strong> Aperfeiçoamento · <strong>Formato:</strong> Presencial · <strong>Carga horária:</strong> 460h</li>
<li><strong>Código DN:</strong> 286.227 · <strong>Código Senac RJ:</strong> 13339 (cadastrado em 07.11.2023)</li>
</ul>
</section>
<section id="requisitos-de-acesso-2" class="level3">
<h3 class="anchored" data-anchor-id="requisitos-de-acesso-2">2. Requisitos de acesso</h3>
<ul>
<li>Idade mínima: 18 anos · Conhecimentos em Windows e navegação na internet.</li>
<li><strong>Aprovação em teste</strong> de conhecimentos específicos de lógica, Windows e internet.</li>
<li>Documentos: identidade, CPF, autodeclaração de conhecimentos em Windows e internet.</li>
</ul>
</section>
<section id="justificativa-2" class="level3">
<h3 class="anchored" data-anchor-id="justificativa-2">3. Justificativa</h3>
<p>Currículo AWS Re/Start concentrado em duas áreas técnicas — <strong>Fundamentos de TI</strong> e <strong>Nuvem AWS</strong> — para preparar o aluno a vagas iniciais de computação em nuvem. Parte técnica predominantemente <strong>prática</strong> (exercícios, laboratórios, projeto de ponta a ponta) e desenvolvimento de <strong>soft skills</strong>. Fundamenta-se no crescimento do mercado de Nuvem (Brasscom: R$ 308 bilhões em investimento entre 2023–2026, ~28% a.a.) e na liderança da AWS em CIPS (Gartner, 12º ano consecutivo em 2022).</p>
</section>
<section id="objetivo-2" class="level3">
<h3 class="anchored" data-anchor-id="objetivo-2">4. Objetivo</h3>
<p>Dar subsídios nas principais ferramentas e recursos da <strong>AWS</strong>, com ênfase em habilidades profissionais exigidas pelo mercado, e <strong>preparar o estudante para o exame de certificação AWS Cloud Practitioner</strong>. Destinado a quem deseja ingressar na área de computação em nuvem ou a profissionais de TI.</p>
</section>
<section id="organização-curricular-2" class="level3">
<h3 class="anchored" data-anchor-id="organização-curricular-2">5. Organização curricular</h3>
<p>Seis unidades curriculares (competências), totalizando <strong>460h</strong>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 83%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Unidade Curricular</th>
<th style="text-align: right;">CH</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>UC1</strong> — Configurar e operar sistema operacional Linux em ambientes de nuvem</td>
<td style="text-align: right;">76h</td>
</tr>
<tr class="even">
<td><strong>UC2</strong> — Planejar, configurar e implementar infraestrutura de redes com segurança em nuvem</td>
<td style="text-align: right;">68h</td>
</tr>
<tr class="odd">
<td><strong>UC3</strong> — Automatizar sistemas e manipular dados em nuvem com linguagem de programação (Python)</td>
<td style="text-align: right;">100h</td>
</tr>
<tr class="even">
<td><strong>UC4</strong> — Identificar e configurar os principais serviços da AWS</td>
<td style="text-align: right;">92h</td>
</tr>
<tr class="odd">
<td><strong>UC5</strong> — Planejar, monitorar e implementar ambientes em nuvem AWS</td>
<td style="text-align: right;">88h</td>
</tr>
<tr class="even">
<td><strong>UC6</strong> — Desenvolver soft skills para o mercado de trabalho</td>
<td style="text-align: right;">36h</td>
</tr>
</tbody>
</table>
<p><strong>Conhecimentos / Habilidades / Atitudes</strong> (síntese por bloco):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Elemento</th>
<th>Síntese</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Conhecimentos</strong></td>
<td>Fundamentos de nuvem (IaaS/SaaS/PaaS, escalabilidade, custos); <strong>Linux</strong> (usuários, diretórios, processos, rede); <strong>redes e VPC</strong> (IP, sub-redes, roteamento, gateways); <strong>segurança</strong> (IAM, Trusted Advisor, ciclo prevenção/detecção/resposta); <strong>Python e Git</strong>, DevOps/CI, <strong>bancos de dados</strong> (RDS, relacionais e NoSQL em nuvem); <strong>serviços AWS</strong> (EC2, S3/EBS/Glacier, Lambda, Route 53, API Gateway, Elastic Beanstalk, CLI, Systems Manager); <strong>monitoramento</strong> (CloudWatch, CloudTrail, Auto Scaling, Load Balancing); <strong>IaC</strong> (JSON/YAML, CloudFormation); conteúdos da certificação <strong>Cloud Practitioner</strong>; soft skills e empregabilidade.</td>
</tr>
<tr class="even">
<td><strong>Habilidades</strong></td>
<td>Operar Linux por linha de comando; configurar redes em nuvem com segurança; programar e automatizar em Python; configurar e gerenciar serviços AWS; analisar logs/eventos; proteger aplicações; aplicar práticas direcionadas à certificação; comunicar-se de forma assertiva e propor soluções.</td>
</tr>
<tr class="odd">
<td><strong>Atitudes/Valores</strong></td>
<td>Ética no uso dos serviços; sigilo no tratamento de dados; responsabilidade e comprometimento; visão sistêmica; postura profissional; proatividade e senso crítico; colaboração e flexibilidade.</td>
</tr>
</tbody>
</table>
<p>As competências de <strong>empregabilidade</strong> (objetivos de carreira, entrevistas, currículo, networking, elevator pitch, trabalho em equipe) são distribuídas ao longo de todas as UCs.</p>
</section>
<section id="orientações-metodológicas-2" class="level3">
<h3 class="anchored" data-anchor-id="orientações-metodológicas-2">6. Orientações metodológicas</h3>
<p>Alinhadas à Proposta Pedagógica Senac (aprendizagem com autonomia, desenvolvimento de competências e Marcas Formativas). Recomenda-se que o docente revise previamente a <strong>plataforma AWS Re/Start</strong> (capacitação e laboratórios). Conceitos de nuvem associados a <strong>situações práticas</strong> com as ferramentas AWS: simulação de problemas com dados reais, <strong>laboratórios do portal Canvas</strong> do programa, estudos de caso e ferramentas interativas (Mentimeter, Kahoot ou similares).</p>
</section>
<section id="avaliação-2" class="level3">
<h3 class="anchored" data-anchor-id="avaliação-2">7. Avaliação</h3>
<p>Avaliação <strong>diagnóstica, formativa e somativa</strong>. Menções por indicador (A / PA / NA), por UC (<strong>D / ND</strong>) e no curso (<strong>AP / RP</strong>). Aprovação exige <strong>D em todas as UCs</strong> e <strong>frequência mínima de 75%</strong>. Recuperação imediata à constatação de dificuldades.</p>
</section>
<section id="recursos-perfil-docente-e-certificação" class="level3">
<h3 class="anchored" data-anchor-id="recursos-perfil-docente-e-certificação">8–12. Recursos, perfil docente e certificação</h3>
<p>Laboratório com internet e projetor; <strong>1 computador por aluno</strong> (Core i5 10ª geração+, Windows 10+, 8GB), navegadores e Office 365; acesso ao <strong>portal AWS Re/Start</strong>. Bibliografia: material digital da plataforma AWS Re/Start. Docente com <strong>experiência em soluções AWS</strong> e ao menos uma certificação ativa (SysOps Associate, Solutions Architect Associate/Professional ou DevOps Engineer Professional) + 1 ano de docência em TI. Certificado em <em>AWS Re/Start — Computação em Nuvem</em>, em <strong>dupla chancela AWS e SENAC RJ</strong>, validade nacional.</p>
</section>
</div>
<div id="tabset-3-2" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-2-tab">
<blockquote class="blockquote">
<p><strong>PTD indisponível.</strong> Não há documento de PTD (<code>.docx</code>) na pasta-fonte oficial — a subpasta <code>Operação/PTD_PPT_anexos</code> está vazia. O único artefato correlato é a <strong>agenda de PTD em planilha</strong> (<code>RE_Start_Agenda_PTD V2.xlsx</code>, em <em>Material de Apoio</em>), que organiza o cronograma das aulas mas não substitui o PTD. Atualizar esta aba quando o PTD oficial for disponibilizado.</p>
</blockquote>
</div>
<div id="tabset-3-3" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-3-tab">
<p><strong>Básica (oficial — do PC)</strong></p>
<ul>
<li>Material digital disponibilizado na <strong>plataforma AWS Re/Start</strong> (currículo oficial, laboratórios e portal Canvas).</li>
</ul>
<p><strong>Complementar (apoio)</strong></p>
<ul>
<li>AWS Skill Builder / AWS Training — preparação para o exame <strong>AWS Certified Cloud Practitioner</strong>.</li>
<li>Espaço Docente Senac — plataformas Cachola e Cubus; Anuário de Tecnologias Educacionais.</li>
</ul>
</div>
<div id="tabset-3-4" class="tab-pane" role="tabpanel" aria-labelledby="tabset-3-4-tab">
<ul>
<li><strong>Ementa do curso:</strong> <a href="fonte/Ementa - AWS ReStart.docx">Ementa — AWS ReStart (.docx)</a></li>
<li><strong>Atividades práticas:</strong> <code>AWS-ATividades.xlsx</code> (e versão <code>.ods</code>), na pasta de origem (<em>Criação / Material de Apoio</em>).</li>
<li><strong>Agenda / cronograma das aulas:</strong> <code>RE_Start_Agenda_PTD V2.xlsx</code> (<em>Material de Apoio</em>).</li>
<li><strong>Regulamento do programa:</strong> <code>Regulamento AWS_SENAC_2023.docx</code> (<em>Material de Apoio</em>).</li>
<li><strong>Material de enxoval / pilotos:</strong> PDFs do programa em <em>ENXOVAL</em> (apresentação do curso e piloto remoto).</li>
</ul>
<blockquote class="blockquote">
<p>Os arquivos não copiados para esta página permanecem na pasta-fonte oficial (SharePoint), por serem planilhas/PDFs de operação; aqui foram copiados apenas o <strong>PC</strong> e a <strong>Ementa</strong>.</p>
</blockquote>
</div>
</div>
</div>
</section>
<section id="histórico-de-atualizações-deste-curso-2" class="level2">
<h2 class="anchored" data-anchor-id="histórico-de-atualizações-deste-curso-2">Histórico de atualizações (deste curso)</h2>
<table class="caption-top table">
<caption>Histórico do material deste curso.</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 62%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Data</th>
<th>O que mudou</th>
<th>Autor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2026-06-23</td>
<td>Página preenchida com PC e materiais a partir dos arquivos oficiais (SharePoint).</td>
<td>Cápsula de Inovação</td>
</tr>
</tbody>
</table>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> De volta ao topo</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Cápsula de Inovação — Coordenação de Tecnologias, SENAC RJ</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Atualizado de forma contínua · ver <a href="./changelog.html">Changelog</a></p>
</div>
  </div>
</footer>




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>